version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.1
      environment:
        PIPENV_VENV_IN_PROJECT: 'true'
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-{{ checksum "Pipfile.lock" }}
        - v1-
    - run:
        name: install dependencies
        command: |
          sudo pip install pipenv
          pipenv install
    - save_cache:
        paths:
        - ./.venv
        key: v1-{{ checksum "Pipfile.lock" }}
    - run:
        name: run tests
        command: |
          pipenv run coverage run --source app/ -m unittest discover app
    - run:
        name: coverage report
        command: |
          pipenv run coverage html --skip-covered
    - store_artifacts:
        path: htmlcov/
        destination: htmlcov/
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
            - develop
            - feature/coverage