version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: "true"
    branches:
      only:
        - master
        - develop
        - feature/coverage

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-{{ checksum "Pipfile.lock" }}
          - v1-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install

      - save_cache:
          paths:
            - ./.venv
          key: v1-{{ checksum "Pipfile.lock" }}

#      - run:
#          name: run tests
#          command: |
#            pipenv run python -m unittest discover app

      - run:
          name: run tests
          command: |
            pipenv run coverage run -m unittest discover app

      - run:
          name: coverage report
          command: |
            pipenv run coverage html

      - store_artifacts:
          path: htmlcov/
          destination: htmlcov/